version: '3.1'

services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - contohlapak_network
    environment:
      MYSQL_DATABASE: contohlapak
      MYSQL_ROOT_PASSWORD: pass
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - contohlapak_network
  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - contohlapak_network
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: pass
  contohlapak:
    container_name: contohlapak
    restart: always
    # image: greyhats13/contohlapak:latest
    build:
      dockerfile: Dockerfile
      context: .
    # ports:
    #   - 9090:9090
    networks:
      - contohlapak_network
    environment:
      - MYSQL_ENABLED=true
      - REDIS_ENABLED=true
      - LOAD_BALANCED=true
      - LISTEN_PORT=9090
      - MYSQL_ADDR=mysql:3306
      - MYSQL_USER=root
      - MYSQL_PASS=pass
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DB=contohlapak
      - REDIS_ADDR=redis:6379
      # - HEADER_AUTH_KEY=X-CONTOHLAPAK-AUTH
      - VIRTUAL_HOST=contohlapak.blast.co.id
      - LETSENCRYPT_HOST=contohlapak.blast.co.id
    depends_on:
      - mysql
      - redis
      - phpmyadmin
  nginx:
    container_name: nginx
    # image: nginx:latest
    build:
      dockerfile: Dockerfile-nginx
      context: .
      # Connects the conf file of the container to the conf file in our folder
    ports:
      - 80:80
      - "443:443"
    networks:
      - contohlapak_network
      # It will start up the nginx only when all api containers have started
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"
    depends_on: 
      - contohlapak
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on: 
      - nginx
networks:
  contohlapak_network:
    driver: bridge
volumes:
  mysql_data:
    driver: local