version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    networks:
      - contohlapak_network
    environment:
      MYSQL_ROOT_PASSWORD: pass
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - contohlapak_network
  contohlapak:
    container_name: contohlapak
    image: contohlapak:latest
    ports:
      - 8080:8080
    networks:
      - contohlapak_network
    environment:
      - MYSQL_ENABLED=true
      - REDIS_ENABLED=true
      - LOAD_BALANCED=false
      - LISTEN_PORT=8080
      - MYSQL_ADDRESS=mysql:3306
      - MYSQL_USER=root
      - MYSQL_PASS=pass
      - MYSQL_DB=contohlapak
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - mysql
      - redis
networks:
  contohlapak_network:
    name: contohlapak_network