version: '3.1'

services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - contohlapak_network
    environment:
      MYSQL_DATABASE: contohlapak
      MYSQL_ROOT_PASSWORD: pass
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - contohlapak_network
  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - contohlapak_network
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: pass
  contohlapak:
    container_name: contohlapak
    restart: always
    image: contohlapak:latest
    ports:
      - 8080:8080
    networks:
      - contohlapak_network
    environment:
      - MYSQL_ENABLED=true
      - REDIS_ENABLED=false
      - LOAD_BALANCED=false
      - LISTEN_PORT=8080
      - MYSQL_ADDRESS=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=pass
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DB=contohlapak
      - REDIS_ADDRESS=redis
    depends_on:
      - mysql
      - redis
      - phpmyadmin
networks:
  contohlapak_network:
    driver: bridge
volumes:
  mysql_data:
    driver: local