version: '3.1'

services:
  db:
    container_name: dockerMySQL
    restart: always
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - contohlapak_network
    environment:
      MYSQL_DATABASE: contohlapak
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: toor
  cache:
    container_name: dockerRedis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - contohlapak_network
  phpmyadmin:
    container_name: admin
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - contohlapak_network
    depends_on:
      - db
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: toor
  contohlapak:
    container_name: contohlapak
    restart: always
    image: contohlapak:latest
    ports:
      - 8080:8080
    networks:
      - contohlapak_network
    environment:
      - MYSQL_ENABLED=true
      - REDIS_ENABLED=false
      - LOAD_BALANCED=false
      - LISTEN_PORT=8080
      - MYSQL_ADDRESS=dockerMySQL
      - MYSQL_PORT=3306
      - MYSQL_USER=docker
      - MYSQL_PASS=password
      - MYSQL_DB=contohlapak
      - REDIS_ADDRESS=dockerRedis
    depends_on:
      - db
      - cache
networks:
  contohlapak_network:
    driver: bridge
volumes:
  mysql_data:
    driver: local